- name: Collect only facts returned by facter
  hosts: all
  gather_facts: true  

  tasks:
     - name: Run an executable and send data to the stdin for the executable
       win_shell: slmgr.vbs /skms (kmseua.bvcorp.corp)
       win_shell: slmgr.vbs /ato
 
