- name: Collect only facts returned by facter
  hosts: all
  gather_facts: false  
  
  tasks:

    - win_command: cmd.exe /c "reg add "HKLM\SYSTEM\CurrentControlSet\services\Tcpip\Parameters" /v "SearchList" /t REG_SZ /d "pac.bvcorp.corp,bureauveritas.com" /f > nul"
      async: 5
      poll: 0
      
    - win_command: cmd.exe /c  slmgr.vbs -ato 
      async: 5
      poll: 0
          
    - win_command: cmd.exe /c slmgr.vbs -skms fku-kms-01.ggg
      async: 5
      poll: 0  
    # - win_shell: slmgr.vbs -skms fsu-kms-01.fsu.edu
     #  args:
      #  executable: cmd

    - name: Adding Registry for Disabiling Server Manager 1st
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: DoNotOpenServerManagerAtLogon
        data: 0x1
        type: dword
        
    - name: Adding Registry for Disabiling Server Manager 2nd
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: CheckedUnattendLaunchSetting
        data: 0x1
        type: dword

    - name: Adding Registry for Disabiling Server Manager 3rd
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: DoNotPopWACConsoleAtSMLaunch
        data: 0x1
        type: dword

# Disable Wallpaper
    - name: Disabling Wallpaper
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
        name: DisableLogonBackgroundImage
        data: 0x1
        type: dword
# Disable IE Enhanced security config for admins
    - name: Disabling IE Enhanced security config for admins
      win_regedit:
         path: HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}
         name: IsInstalled
         data: 0x0
         type: dword
         
# Disable UAC
    - name: Disable UAC
      win_regedit:
         path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
         name: ConsentPromptBehaviorAdmin
         data: 0x0
         type: dword
      win_regedit:
         path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
         name: EnableLUA
         data: 0x0
         type: dword

    - name: Copy a folder recursively where the source is on the remote host
      win_copy:
        src: \\103.206.211.143\Packages
        dest: C:\Packages
        remote_src: yes
