- name: Collect only facts returned by facter
  hosts: all
  gather_facts: false  
  
  tasks:
     - name: Run an executable and send data to the stdin for the executable
       win_command: cscript.exe slmgr.vbs /skms kmseua.bvcorp.corp
       args:
       chdir: C:\Windows\System32
       #win_shell: cscript  C:\windows\system32\slmgr.vbs -ato
 
