- name: Collect only facts returned by facter
  hosts: all
  gather_facts: true  
  become: yes
  become_method: enable
  
  tasks:
     - name: Run an executable and send data to the stdin for the executable
       win_command: cscript  C:\windows\system32\slmgr.vbs -skms kmseua.bvcorp.corp
       win_shell: cscript  C:\windows\system32\slmgr.vbs -ato
 
