- name: Collect only facts returned by facter
  hosts: all
  gather_facts: false  
  
  tasks:
    
    - win_command: cmd.exeslmgr.vbs -ato 
      async: 5
      poll: 0
          
    - win_command: cmd.exe /c slmgr.vbs -skms fku-kms-01.ggg
      async: 5
      poll: 0  
    # - win_shell: slmgr.vbs -skms fsu-kms-01.fsu.edu
     #  args:
      #  executable: cmd

    - name: Adding Registry for Disabiling Server Manager 1st
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: DoNotOpenServerManagerAtLogon
        data: 0x1
        type: dword
        
    - name: Adding Registry for Disabiling Server Manager 2nd
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: CheckedUnattendLaunchSetting
        data: 0x1
        type: dword

    - name: Adding Registry for Disabiling Server Manager 3rd
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\ServerManager
        name: DoNotPopWACConsoleAtSMLaunch
        data: 0x1
        type: dword

# Disable Wallpaper
    - name: Disabling Wallpaper
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
        name: DisableLogonBackgroundImage
        data: 0x1
        type: dword
# Enabling Remote Desktop 
    - name: Enabling Remote Desktop
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableCdm
         data: 0x1
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableLPT
         data: 0x1
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableCcm
         data: 0x1
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableClip
         data: 0x0
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableCam
         data: 0x1
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fDisableAudioCapture
         data: 0x1
         type: dword
      win_regedit:
         path: HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
         name: fForceClientLptDef
         data: 0x0
         type: dword
         
