- name: Collect only facts returned by facter
  hosts: all
  gather_facts: false  
  
  tasks:
     - name: Run an executable and send data to the stdin for the executable
       #win_command: cscript.exe C:\windows\system32\slmgr.vbs -skms fsu-kms-01.fsu.edu
       win_shell: cscript.exe slmgr.vbs -skms fsu-kms-01.fsu.edu
       win_command: cscript  C:\windows\system32\slmgr.vbs -ato
 
