- name: Collect only facts returned by facter
  hosts: all
  gather_facts: false  
  
  tasks:
    
    - win_command: cmd.exeslmgr.vbs -ato 
      async: 5
      poll: 0
      
    - win_command: cmd.exe /c slmgr.vbs -skms fku-kms-01.ggg
      async: 5
      poll: 0      
    # - win_shell: slmgr.vbs -skms fsu-kms-01.fsu.edu
     #  args:
      #  executable: cmd
